# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pHost', models.CharField(max_length=100)),
                ('pPort', models.IntegerField()),
                ('pProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIndex.testProject')),
            ],
        ),
    ]
