# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iName', models.CharField(max_length=100)),
                ('iurl', models.CharField(max_length=100)),
                ('iHttp', models.CharField(max_length=10)),
                ('iType', models.CharField(max_length=10)),
                ('iStatus', models.IntegerField(choices=[(1, '\u5df2\u901a\u8fc7'), (0, '\u672a\u901a\u8fc7'), (2, '\u7533\u8bf7\u4e2d')], default=2)),
                ('iTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIndex.testTask')),
            ],
        ),
    ]
