# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoIndex', '0002_testinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiBoby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boby_type', models.CharField(choices=[('raw', 'raw'), ('form-data', 'form-data')], max_length=100)),
                ('boby_content', models.CharField(blank=True, max_length=100, null=True)),
                ('boby_key', models.CharField(max_length=100, null=True)),
                ('boby_values', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='apiHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, null=True)),
                ('key_description', models.CharField(blank=True, max_length=100, null=True)),
                ('key_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='apiParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, null=True)),
                ('key_description', models.CharField(blank=True, max_length=100, null=True)),
                ('key_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testinterface',
            name='iStatus',
            field=models.IntegerField(choices=[(0, '\u672a\u901a\u8fc7'), (1, '\u5df2\u901a\u8fc7'), (2, '\u7533\u8bf7\u4e2d')], default=2),
        ),
        migrations.AddField(
            model_name='apiparams',
            name='apiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIndex.testInterface'),
        ),
        migrations.AddField(
            model_name='apiheader',
            name='apiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIndex.testInterface'),
        ),
        migrations.AddField(
            model_name='apiboby',
            name='apiId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIndex.testInterface'),
        ),
    ]
