# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoIndex', '0003_auto_20190514_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiboby',
            name='boby_type',
            field=models.CharField(choices=[('raw', 'raw'), ('form-data', 'form-data'), ('x-www-form-urlencoded', 'x-www-form-urlencoded')], max_length=100),
        ),
    ]
