# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoIndex', '0004_auto_20190514_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apiBoby',
            new_name='apiBody',
        ),
        migrations.RenameField(
            model_name='apibody',
            old_name='boby_content',
            new_name='body_content',
        ),
        migrations.RenameField(
            model_name='apibody',
            old_name='boby_key',
            new_name='body_key',
        ),
        migrations.RenameField(
            model_name='apibody',
            old_name='boby_type',
            new_name='body_type',
        ),
        migrations.RenameField(
            model_name='apibody',
            old_name='boby_values',
            new_name='body_values',
        ),
    ]
